# Generated by Django 3.2.7 on 2021-09-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image_url',
            new_name='coverUrl',
        ),
    ]
