# Generated by Django 3.2.7 on 2021-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_image_url_person_coverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
