# Generated by Django 3.2.7 on 2021-10-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_person_coverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='detailscouverture',
            field=models.ImageField(null=True, upload_to='person-detailcouverture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personImage',
            field=models.ImageField(null=True, upload_to='person-profile/%Y/%m/%d'),
        ),
    ]
