# Generated by Django 3.2.7 on 2021-10-03 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAccount', '0003_auto_20211003_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='Customer',
        ),
    ]
