# Generated by Django 3.2.7 on 2021-10-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20211006_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
