# Generated by Django 3.2.7 on 2021-10-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar-images'),
        ),
    ]
